// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package datastore

type Tag struct {
	ID        int64
	Name      string
	CreatedAt int64
	UpdatedAt int64
	DeletedAt int64
}

type Token struct {
	Token     string
	Type      string
	Email     string
	ExpiresAt int64
	DeletedAt int64
}

type User struct {
	Email      string
	Name       string
	Password   []byte
	Salt       []byte
	CreatedAt  int64
	UpdatedAt  int64
	VerifiedAt int64
	DeletedAt  int64
}
