# STEP 1 build app
FROM golang:1.24.1 AS builder
LABEL stage=intermediate

WORKDIR /bin
ADD . .

RUN make dependencies
RUN make build-prod

# STEP 2 build small image with app
FROM alpine:latest

WORKDIR /
COPY --from=builder /bin/app .
RUN mkdir -p /tmp

EXPOSE 3000 3010

ENTRYPOINT [ "/app" ]