name: Build & Release

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"

    - name: Update Dependencies
      run: make dependencies

    - name: Compile Templates
      run: make templ-generate

    - name: Check Dependencies Changes
      run: if [ -n "$(git status --porcelain)" ]; then git status --porcelain && exit 1; fi

    - name: Check code
      run: make check-cicd

    - name: Test
      run: go test -race -v -timeout 30s ./... -coverprofile cover.out

    - name: Show Test Coverage
      run: go tool cover -func cover.out

    - name: Build
      run: make build

  release:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: echo building app...
