// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package common

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func FormValidation() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script>\n    function validateForm(id) {\n      const form = document.getElementById(id);\n\n      form.addEventListener(\"submit\", function (e) {\n        e.preventDefault();\n        form.classList.add(\"validated\");\n        if (form.checkValidity()) {\n          form.submit();\n          return\n        }\n\n        form.querySelectorAll(\":valid\").forEach(function(el) {\n          if (el.classList.contains(\"form-control\")) {\n            el.classList.add(\"bg-neutral-50\");\n            el.classList.add(\"dark:bg-dark-2\");\n            el.classList.remove(\"bg-danger-100\");\n            el.classList.remove(\"dark:bg-light-100\");\n          }\n        });\n\n        form.querySelectorAll(\":invalid\").forEach(function(el, i) {\n          if (el.classList.contains(\"form-control\")) {\n            el.classList.remove(\"bg-neutral-50\");\n            el.classList.remove(\"dark:bg-dark-2\");\n            el.classList.add(\"ring-danger-500\");\n            el.classList.add(\"bg-danger-100\");\n\n            if (i == 0) {\n              el.focus();\n            }\n          }\n        });\n      });\n    }\n  </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
