// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package common

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func PasswordToggle() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_PasswordToggle_f339`,
		Function: `function __templ_PasswordToggle_f339(){function initializePasswordToggle(toggleSelector) {
    const icon = document.getElementsByClassName(toggleSelector)[0];
    let password = document.getElementById('password');

    icon.addEventListener('click', function() {
      if (password.type == "password") {
        password.type = "text";
        icon.classList.add("ri-eye-off-line");
        icon.classList.remove("ri-eye-line");
      } else {
        password.type = "password";
        icon.classList.add("ri-eye-line");
        icon.classList.remove("ri-eye-off-line");
      }
    });
  }

  initializePasswordToggle('toggle-password');
}`,
		Call:       templ.SafeScript(`__templ_PasswordToggle_f339`),
		CallInline: templ.SafeScriptInline(`__templ_PasswordToggle_f339`),
	}
}

var _ = templruntime.GeneratedTemplate
